apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: ubuntu
    image: weibeld/ubuntu-networking
    command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
  - name: ubuntu
    image: weibeld/ubuntu-networking
    command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
spec:
  containers:
  - name: ubuntu
    image: weibeld/ubuntu-networking
    command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
spec:
  containers:
  - name: ubuntu
    image: weibeld/ubuntu-networking
    command: ["sleep", "infinity"]
